import Head from 'next/head';
import Header from '../components/Header';
import Hero from '../components/Hero';
import { MidSection } from '../components/MidSection';
import { countPlayers } from '../utils';
import { GetServerSideProps } from 'next';

export default function Home({ count }) {
  return (
    <>
      <Head>
        <title>G0 GO MATHS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='bg-white'>
          <Header />
          <Hero />
          <MidSection count={count} />
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  // Fetch data from an API or database
  const count = await countPlayers();
  // Return the data as props to the component
  return {
    props: {
      count,
    },
  };
}
