import Head from 'next/head';
import Header from '../components/Header';
import { getDocs, collection } from 'firebase/firestore';
import { db } from '../firebase';
import { useState, useEffect } from 'react';

export default function LeaderBoard() {
  const [leaderBoard, setLeaderBoard] = useState([]);
  const getLeaderBoard = async () => {
    const query = await getDocs(collection(db, 'players'));
    setLeaderBoard(query.docs.map((doc) => doc.data()));
  };
  const sortedLeaderBoard = [...leaderBoard].sort((a, b) => b.score - a.score);

  useEffect(() => {
    getLeaderBoard();
  }, []);
  return (
    <>
      <Head>
        <title>G0 GO MATHS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        <div className='px-6'>
          <div className='pt-4 '>
            <h1 className='text-4xl md:text-6xl xl:text-7xl font-bold tracking-tight mb-6 text-center '>
              Leader <span className='text-blue-600'> Board</span>
            </h1>
          </div>
          <div className='flex flex-col'>
            <div className='overflow-x-auto sm:-mx-6 lg:-mx-8'>
              <div className='inline-block min-w-full py-2 sm:px-6 lg:px-8'>
                <div className='overflow-hidden'>
                  <table className='min-w-full text-left text-sm font-light'>
                    <thead className='border-b bg-white font-medium '>
                      <tr>
                        <th scope='col' className='px-6 py-4'>
                          #
                        </th>
                        <th scope='col' className='px-6 py-4'>
                          NICKNAME
                        </th>
                        <th scope='col' className='px-6 py-4'>
                          SCORE
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      {sortedLeaderBoard.map((player, index) => (
                        <tr key={index} className='border-b bg-neutral-100 '>
                          <td className='whitespace-nowrap px-6 py-4 font-medium'>
                            {index + 1}
                          </td>
                          <td className='whitespace-nowrap px-6 py-4'>
                            {player.nickname}
                          </td>
                          <td className='whitespace-nowrap px-6 py-4'>
                            {player.score}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
