import Head from 'next/head';
import Header from '../components/Header';
import { useState, useEffect } from 'react';
import { db } from '../firebase';
import PickMode from '../components/PickMode';
import { getDoc, doc } from 'firebase/firestore';
import UserForm from '../components/UserForm';
import Loading from '../components/Loading';

export default function Play() {
  const [loading, setLoading] = useState(false);
  const [nickname, setNickname] = useState('');
  const [playerScore, setPlayerScore] = useState(0); // [1
  const getUserName = async () => {
    if (typeof window !== 'undefined') {
      setLoading(true);
      const userId = localStorage.getItem('playerId');
      if (userId) {
        const docRef = doc(db, 'players', userId);
        const docSnapshot = await getDoc(docRef);
        if (docSnapshot.exists()) {
          const data = docSnapshot.data();
          setNickname(data.nickname);
          setPlayerScore(data.score);
        } else {
          console.log('No such document!');
        }
      }
      setLoading(false);
    }
  };
  console.log(playerScore);

  useEffect(() => {
    getUserName();
  }, []);

  return (
    <>
      <Head>
        <title>G0 GO MATHS</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Header />
        {loading ? (
          <>
            <Loading />
          </>
        ) : (
          <>
            {nickname ? (
              <>
                <PickMode nickname={nickname} playerScore={playerScore} />
              </>
            ) : (
              <>
                <UserForm getUserName={getUserName} />
              </>
            )}
          </>
        )}
      </main>
    </>
  );
}
